language: R
sudo: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/lib
    - $HOME/.npm

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

install: travis_wait 60 mvn install
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

pandoc_version: 2.1.1

deploy:
  provider: script
  script: netlify deploy --dir="_book/" --prod
  skip_cleanup: true